#ifndef __GBM_CONSTANTS_H__
#define __GBM_CONSTANTS_H__

#include <stdint.h>

#define UGB_GPU_MODE00_CLOCKS 204
#define UGB_GPU_MODE01_CLOCKS 450
#define UGB_GPU_MODE10_CLOCKS 80
#define UGB_GPU_MODE11_CLOCKS 172

#define UGB_GPU_SCREEN_W  160
#define UGB_GPU_SCREEN_H  144
#define UGB_GPU_SCREEN_VH 154

#define UGB_VRAM_LOW  0x8000
#define UGB_VRAM_HIGH 0x9FFF

#endif // __GBM_CONSTANTS_H__
